"""This is a place to store shared variables"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/config.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/API/config.ipynb 2
# This is a place to store shared variables
